#!/usr/bin/env python3
"""
Compare traces generated by PIN and DynamoRIO tracers.
Validates that both produce semantically equivalent traces.
"""

import struct
import sys
import argparse

# Trace instruction format (from trace_instruction.h)
# struct input_instr {
#     unsigned long long ip;                       // 8 bytes
#     unsigned char is_branch;                     // 1 byte
#     unsigned char branch_taken;                  // 1 byte
#     unsigned char destination_registers[2];      // 2 bytes
#     unsigned char source_registers[4];           // 4 bytes
#     unsigned long long destination_memory[2];    // 16 bytes
#     unsigned long long source_memory[4];         // 32 bytes
# };
# Total: 64 bytes

INSTR_SIZE = 64

def read_instruction(f):
    """Read one instruction from trace file."""
    data = f.read(INSTR_SIZE)
    if len(data) != INSTR_SIZE:
        return None
    
    # Unpack the instruction
    ip = struct.unpack('<Q', data[0:8])[0]
    is_branch = data[8]
    branch_taken = data[9]
    dest_regs = list(data[10:12])
    src_regs = list(data[12:16])
    dest_mem = struct.unpack('<QQ', data[16:32])
    src_mem = struct.unpack('<QQQQ', data[32:64])
    
    return {
        'ip': ip,
        'is_branch': is_branch,
        'branch_taken': branch_taken,
        'dest_regs': dest_regs,
        'src_regs': src_regs,
        'dest_mem': list(dest_mem),
        'src_mem': list(src_mem)
    }

def format_instruction(instr):
    """Format instruction for display."""
    parts = [f"IP: 0x{instr['ip']:016x}"]
    
    if instr['is_branch']:
        taken = "taken" if instr['branch_taken'] else "not-taken"
        parts.append(f"Branch: {taken}")
    
    # Filter out zero registers
    src_regs = [r for r in instr['src_regs'] if r != 0]
    if src_regs:
        parts.append(f"SrcRegs: {src_regs}")
    
    dest_regs = [r for r in instr['dest_regs'] if r != 0]
    if dest_regs:
        parts.append(f"DstRegs: {dest_regs}")
    
    # Filter out zero memory addresses
    src_mem = [f"0x{m:016x}" for m in instr['src_mem'] if m != 0]
    if src_mem:
        parts.append(f"SrcMem: {src_mem}")
    
    dest_mem = [f"0x{m:016x}" for m in instr['dest_mem'] if m != 0]
    if dest_mem:
        parts.append(f"DstMem: {dest_mem}")
    
    return ", ".join(parts)

def compare_traces(pin_file, dr_file, max_diff=10, verbose=False):
    """Compare two trace files."""
    print(f"Comparing traces:")
    print(f"  PIN trace:       {pin_file}")
    print(f"  DynamoRIO trace: {dr_file}")
    print()
    
    with open(pin_file, 'rb') as f_pin, open(dr_file, 'rb') as f_dr:
        idx = 0
        differences = 0
        mismatches = []
        
        while True:
            pin_instr = read_instruction(f_pin)
            dr_instr = read_instruction(f_dr)
            
            # Check if both finished
            if pin_instr is None and dr_instr is None:
                break
            
            # Check if one finished early
            if pin_instr is None:
                print(f"ERROR: PIN trace ended early at instruction {idx}")
                print(f"DynamoRIO trace has more instructions")
                return False
            
            if dr_instr is None:
                print(f"ERROR: DynamoRIO trace ended early at instruction {idx}")
                print(f"PIN trace has more instructions")
                return False
            
            # Compare instructions
            match = True
            diff_fields = []
            
            # Compare IP (must match exactly)
            if pin_instr['ip'] != dr_instr['ip']:
                match = False
                diff_fields.append('IP')
            
            # Compare branch info
            if pin_instr['is_branch'] != dr_instr['is_branch']:
                match = False
                diff_fields.append('is_branch')
            elif pin_instr['is_branch'] and pin_instr['branch_taken'] != dr_instr['branch_taken']:
                match = False
                diff_fields.append('branch_taken')
            
            # Compare registers (note: register IDs may differ between PIN and DR)
            # We'll do a lenient comparison - check if both have same number of registers
            pin_src_regs = [r for r in pin_instr['src_regs'] if r != 0]
            dr_src_regs = [r for r in dr_instr['src_regs'] if r != 0]
            if len(pin_src_regs) != len(dr_src_regs):
                # This is expected due to different register encoding
                if verbose:
                    diff_fields.append(f'src_regs_count({len(pin_src_regs)} vs {len(dr_src_regs)})')
            
            pin_dest_regs = [r for r in pin_instr['dest_regs'] if r != 0]
            dr_dest_regs = [r for r in dr_instr['dest_regs'] if r != 0]
            if len(pin_dest_regs) != len(dr_dest_regs):
                if verbose:
                    diff_fields.append(f'dest_regs_count({len(pin_dest_regs)} vs {len(dr_dest_regs)})')
            
            # Compare memory addresses (should match exactly)
            pin_src_mem = [m for m in pin_instr['src_mem'] if m != 0]
            dr_src_mem = [m for m in dr_instr['src_mem'] if m != 0]
            if pin_src_mem != dr_src_mem:
                match = False
                diff_fields.append('src_mem')
            
            pin_dest_mem = [m for m in pin_instr['dest_mem'] if m != 0]
            dr_dest_mem = [m for m in dr_instr['dest_mem'] if m != 0]
            if pin_dest_mem != dr_dest_mem:
                match = False
                diff_fields.append('dest_mem')
            
            if not match:
                differences += 1
                mismatches.append({
                    'idx': idx,
                    'fields': diff_fields,
                    'pin': pin_instr,
                    'dr': dr_instr
                })
                
                if differences <= max_diff:
                    print(f"MISMATCH at instruction {idx}:")
                    print(f"  Fields differ: {', '.join(diff_fields)}")
                    print(f"  PIN: {format_instruction(pin_instr)}")
                    print(f"  DR:  {format_instruction(dr_instr)}")
                    print()
            
            idx += 1
        
        print(f"Comparison complete:")
        print(f"  Total instructions: {idx}")
        print(f"  Mismatches: {differences}")
        
        if differences == 0:
            print("  ✅ TRACES MATCH PERFECTLY!")
            return True
        else:
            print(f"  ❌ {differences} differences found")
            if differences > max_diff:
                print(f"  (Only showing first {max_diff} mismatches)")
            return False

def main():
    parser = argparse.ArgumentParser(description='Compare PIN and DynamoRIO traces')
    parser.add_argument('pin_trace', help='PIN trace file')
    parser.add_argument('dr_trace', help='DynamoRIO trace file')
    parser.add_argument('--max-diff', type=int, default=10, 
                       help='Maximum number of differences to show (default: 10)')
    parser.add_argument('-v', '--verbose', action='store_true',
                       help='Show verbose output including register count differences')
    
    args = parser.parse_args()
    
    success = compare_traces(args.pin_trace, args.dr_trace, args.max_diff, args.verbose)
    sys.exit(0 if success else 1)

if __name__ == '__main__':
    main()
