# Simple Makefile for test program
CC=gcc
CFLAGS=-O2 -g

all: test_program

test_program: test_program.c
	$(CC) $(CFLAGS) -o test_program test_program.c

clean:
	rm -f test_program

.PHONY: all clean
